name: Slack Notification on Push

on:
  push:
    branches: [ main ]

jobs:
  notify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Send Update Notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"<https://github.com/STUDIO-Construction/StudFinderWiki|StudFinderWiki> contents updated 📖"}' $SLACK_WEBHOOK_URL